version: '3.1'

services:
  dev-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: puser
      POSTGRES_PASSWORD: example
      POSTGRES_DB: nest
  adminer:
    image: adminer    
    ports:
      - 8080:8080